env:
    browser: true
    # for require calls
    node: true
    es2021: true
globals:
    G_IS_DEV: "readonly"
    assert: "readonly"
    assertAlways: "readonly"
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
    sourceType: "module"
plugins:
    - "@typescript-eslint"
    - "prettier"
rules:
    prettier/prettier: error
    no-unused-vars: off
    no-prototype-builtins: off
